### PR TITLE
adding icees_covid_features.yml

### PR DESCRIPTION
**Pull request by Sharma05**
Added a new  icees_covid_features.yml file that is a modification of existing features.yml. I added N3C elements, EPR elements and EPR SNPs. Some of the bioLinkTypes are missing.

### CODE REVIEW

**Comment by xu-hao** [comment]
Hi Priya. Thankd for creating the yaml spec. I reviewed it and some of the fields are empty such at  "maximum", "minimum", or "enum". icees-api will not be able to use the spec unless one of the following:
1. if one of those fields need to be filled in, fill those in
2. if one of those fields do not need to be filled in, remove the fields
Could you make the changes?

**Comment by Sharma05** [comment]
> Hi Priya. Thankd for creating the yaml spec. I reviewed it and some of the fields are empty such at "maximum", "minimum", or "enum". icees-api will not be able to use the spec unless one of the following:
> 
> 1. if one of those fields need to be filled in, fill those in
> 2. if one of those fields do not need to be filled in, remove the fields
>    Could you make the changes?

Hi Hao, sure! Those fields that are empty are not from N3C or EPR elements list that was provided to me. That is from the previous features.yml. But I can definitely fill those if you or @karafecho can point me to the file that has those fields. Thank you.

**Comment by xu-hao** [comment]
An example is `ErythrocyteSedimentationRate`.

**Comment by karafecho** [comment]
@Sharma05 @xu-hao : To clarify, we are planning to use flags for all laboratory metrics, e.g., ErythrocyteSedimentationRate. I've asked @patrickkwang to look into existing code, e.g., LOINC2HPO, to standardize across existing flags. Ideally, we'd like to enumerate this as String = 'Low', 'Normal', 'High'.

**Comment by karafecho** [comment]
@Sharma05 : Please add "Dx" to the N3C disease elements, as was done for "HypertensionDx". Also perhaps you can remind me why we did not include the labs? Was it just because the initial patient data pull did not include them?

**Comment by Sharma05** [comment]
> @Sharma05 : Please add "Dx" to the N3C disease elements, as was done for "HypertensionDx". I will approve the PR after this change, which should be pretty easy.
> 
> Also, the enumeration for labs is slightly different than what we originally agreed to: for each lab X, we have X, X_flag_first, X_flag_last; flags rare enumerated as 'low, normal, high'. This is lower priority so can be accomplished at a later date.
> 
> Thanks!

@karafecho Sure, I will add Dx to all the N3C elements for all the diseases mentioned. As far as I remember I did include labs and they are in the yaml file [https://github.com/Sharma05/icees-api/blob/master/config/icees_covid_features.yml]. Please let me know if you still don't see them. And I will adjust the flags according to your latest request. Thank you

**Comment by karafecho** [comment]
@Sharma05 : When do you expect to complete the task above? We need to close this PR. Also, I found a typo:   ChronicKidneyDisese (should be ChronicKidneyDisease).

**Comment by karafecho** [comment]
@Sharma05 : Also, please replace "Environment" with "EnvironmentalExposure". I also would like to map to more than one Biolink entity, where appropriate. So, for chemicals, please enumerate as follows:

AvgDailyCOExposure_2:
type: integer   
minimum: 1   
maximum: 5      
biolinkType: ChemicalSubstance, ChemicalExposure

**Comment by Sharma05** [comment]
@karafecho Hi Kara, I have made all the above changes as per your request from last week, Please let me know if you require anything else to be changed.

**Comment by karafecho** [comment]
Thanks, @Sharma05 ! 

I noticed that the "Dx" is missing from a few diagnoses.

Also, for medication, I think we need to add "ChemicalExposure" to the list of Biolink entities.

Thanks!

**Comment by Sharma05** [comment]
@karafecho Done! Let me know if you find something else that needs to be addressed. 
Thanks

**Review by karafecho — COMMENTED** [review]
@Sharma05 : This is close, but a few of the exposures (SmokingStatus, PM2.5, etc) need to map to two Biolink entities: ChemicalSubstance and ChemicalExposure. After you make that change, I think we should be ready to merge. We may identify a few minor issues as my QC check was pretty fast, but I think we're mostly good to go.

**Comment by Sharma05** [comment]
> @Sharma05 : This is close, but a few of the exposures (SmokingStatus, PM2.5, etc) need to map to two Biolink entities: ChemicalSubstance and ChemicalExposure. After you make that change, I think we should be ready to merge. We may identify a few minor issues as my QC check was pretty fast, but I think we're mostly good to go.

@karafecho Changes have been made! thanks

**Review by karafecho — APPROVED** [review]

**Comment by karafecho** [comment]
@patrickkwang : Please proceed with the merge. Thanks!

**Comment by karafecho** [comment]
@patrickkwang : Please proceed with the merge. Thanks!

**Pull request merged**
