### PR TITLE
Add supporting-data-source attributes

### PR DESCRIPTION
**Pull request by patrickkwang**

### CODE REVIEW

**Comment by patrickkwang** [comment]
We should also add `attribute_source` (what is the CURIE for ICEES?) and `value_url`, where available.

**Comment by patrickkwang** [comment]
As far as I can tell, there are no standardized identifiers for Translator services yet, so I'm going to separate the `attribute_source` from this PR. See #138.

**Review by karafecho — COMMENTED** [review]
A few corrections and additional URLs:

US Department of Transportation, Federal Highway Administration, Highway Performance Monitoring System. http://www.fhwa.dot.gov/
policyinformation/travel_monitoring/pubs/aadt/ 

US Census Bureau. TIGER/Line®Shapefiles and TIGER/Line®Files. http://www.
census.gov/geo/maps-data/data/tiger-line.html 

US Census Bureau American Community Survey socio-economic exposures data https://www.census.gov/programs-surveys/acs/data.html

North Carolina Department of Environmental Quality concentrated animal farming operations
https://deq.nc.gov/about/divisions/water-resources/water-resources-permits/wastewater-branch/animal-feeding-operation-permits/animal-facility-map

North Carolina Department of Environmental Quality landfill exposures data
https://deq.nc.gov/about/divisions/waste-management/waste-management-rules-data/waste-management-gis-maps

National Center for Education Statistics public school exposures data
https://nces.ed.gov/datatools/

Also, are we treating edge attributes similar to the way COHD is treating them? See Casey's comment here: https://github.com/NCATSTranslator/minihackathons/issues/47#issuecomment-865160530

**Comment by patrickkwang** [comment]
Thanks, @karafecho. The data that I've added here is just for testing and doesn't need to be correct or complete. The data sources will be configurable, so we should add this data to the asthma instance deployment.

**Comment by patrickkwang** [comment]
I'd like to add information about how to configure each deployment, but I think that can be part of a larger documentation update. See #139.

**Comment by karafecho** [comment]
We should also add the primary data sources listed here to the ICEES+ COVID instance. The ICEES+ DILI instance only pulls data from DILIN participant data, Augmentin DILI subset.

**Review by xu-hao — APPROVED** [review]

**Pull request merged**
