### PR TITLE
DILI Use Case Mapping Completed

### PR DESCRIPTION
**Pull request by Sharma05**
@karafecho Completed the DILI Use Case.

### CODE REVIEW

**Comment by xu-hao** [comment]
@Sharma05 The pull request contains changes to files that are not identifiers. Could you rebase the current master and send another pull request that contains only changes to files that are identifiers? thanks.

**Comment by karafecho** [comment]
Also, Priya, can you move process_for_mapping.txt to [this location](https://github.com/NCATS-Tangerine/icees-api/tree/master/docs)? Thanks!

**Comment by xu-hao** [comment]
@Sharma05 all_features.yaml has quite a few changes that don't seem to be related to DILI. Could you check if you are changing the whitespaces and not include those in the pull request. Thanks!

**Comment by karafecho** [comment]
@xu-hao : I think that I was the last person to sign-off on all_features.yaml. At one point, I was working from @Sharma05 's branch, per Patrick's request, but my PR was successfully merged with master, so I don't think any updates in Priya's branch are relevant at this point?

**Comment by Sharma05** [comment]
> @Sharma05 all_features.yaml has quite a few changes that don't seem to be related to DILI. Could you check if you are changing the whitespaces and not include those in the pull request. Thanks!

@xu-hao @karafecho thee all_features file I took it from the master branch NCATS-Tangerine:master issuing that was the latest. Otherwise, I have not made any changes to that file. Thanks. @karafecho -  I did use the updated headers for identifiers.yml but I did not do any entry on all_features.yaml which you took care off. Thanks. Let me know if I have to do something with identifiers.yml.

**Comment by xu-hao** [comment]
@Sharma05 Please remove all_features.yaml from you pull request. When you check in the change you can just add identifier.yml to your commit. that way you only have the files you want to change in pr.

**Pull request closed without merging**
